### ISSUE TITLE
Using RACK_ENV to infer application environment is problematic

### ISSUE THREAD

**Issue by alassek** [svoop/dry-credentials#1]
The history of RACK_ENV is [complicated](https://github.com/rack/rack/pull/831) but it's safe to say its role has been widely misunderstood for years. I blame Rails + Heroku for this confusion.

I think the best practice here is to choose a sensible default, but provide a way for the user to indicate how to derive this information.

Consider the [dry-system `env` plugin](https://dry-rb.org/gems/dry-system/1.0/plugins/#application-environment) for an approach to this problem.

**Comment by alassek** [comment]
Looking at your actual implementation, I think this issue is invalid. Looks like this can already be done.

**Comment by svoop** [comment]
Interesting, I never gave much thought to the difference between `RACK_ENV` and the framework environment.

After [reading this merge](https://github.com/sinatra/sinatra/pull/984), `APP_ENV` appears a better default – and leave `RACK_ENV` out of the equation. What do you think?

**Comment by alassek** [comment]
I hadn't read that PR, good call out. I think `APP_ENV` sounds like a reasonable default.

**Comment by svoop** [comment]
`APP_ENV` is it, thanks for the hint, @alassek !
